### ISSUE TITLE
Error setiap kali menggunakan cover image

### ISSUE THREAD

**Issue by rizafahmi** [deeptechid/forem#1]
**Describe the bug**

Selalu error setiap kali membuat artikel baru dengan cover image. Proses upload image berhasil dan sudah tampil, namun ketika disimpan terjadi error `main_image: is not a valid URL`.

**To Reproduce**
1. Write a post
2. isi judul, isi konten
3. Upload cover image
4. Simpan artikel
5. error muncul

**Expected behavior**

Seharusnya artikel berhasil disimpan. Atau sekalian hilangkan fitur cover image. Meskipun akan kurang menarik secara visual nantinya.

**Screenshots**
<img width="823" alt="Screen Shot 2020-09-10 at 08 26 43" src="https://user-images.githubusercontent.com/1147918/92671627-f7daf580-f340-11ea-9855-14ba6a566d2d.png">

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.6
- Browser, version: Safari 13.1.2, Firefox 79

**Smartphone (please complete the following information):**

**Additional context**

**Comment by giosakti** [comment]
Boleh dicoba lagi sekarang?
backend image sudah diganti ke kombinasi S3 + Cloudinary

**Comment by giosakti** [comment]
konfirmasi, ini sudah jalan sekarang
