### ISSUE TITLE
Error ketika suggest podcast

### ISSUE THREAD

**Issue by rizafahmi** [deeptechid/forem#2]
**Describe the bug**

Ketika submit podcast suggestion, terjadi error 403 forbidden

**To Reproduce**
1. login
2. klik menu podcast
3. Klik suggest a podcast
4. Isi form
5. Submit

**Expected behavior**

podcast berhasil didaftarkan

**Screenshots**
<img width="1440" alt="Screen Shot 2020-09-28 at 08 59 51" src="https://user-images.githubusercontent.com/1147918/94383373-0c552580-016a-11eb-99fc-1bf86e6615d4.png">

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.6
- Browser, version: safari 13.1.12

**Comment by giosakti** [comment]
konfirmasi, ini sudah jalan sekarang
setelah konfigurasi s3 diperbaiki
