### ISSUE TITLE
Form Registrasi Sulit Terlihat

### ISSUE THREAD

**Issue by petrabarus** [deeptechid/forem#6]
**Describe the bug**

Form follow up setelah registrasi susah terbaca

**To Reproduce**

1. Registrasi di diskusi.tech community

**Expected behavior**

Form follow up jelas terlihat.

**Screenshots**

<img width="1364" alt="Screen Shot 2020-09-29 at 9 26 03 AM" src="https://user-images.githubusercontent.com/523289/94506041-abdfea00-0236-11eb-9314-64a287e1e768.png">
<img width="1343" alt="Screen Shot 2020-09-29 at 9 26 12 AM" src="https://user-images.githubusercontent.com/523289/94506048-ae424400-0236-11eb-8400-ef05c1dc991d.png">

**Desktop (please complete the following information):**

- OS, version: Mac 10.13.6
- Browser, version: Firefox 68.8.0esr

**Comment by giosakti** [comment]
Oke siap, kita juga lagi track isunya di https://github.com/forem/forem/issues/10333 kalau ngga ada kabar dari upstream nanti kita override aja CSS-nya

**Comment by giosakti** [comment]
![scr5](https://user-images.githubusercontent.com/524078/94527469-36d5da00-0261-11eb-9299-87bbb09ce609.PNG)

workaround untuk saat ini bisa klik invisible check-box

**Comment by giosakti** [comment]
Isu ini sudah diperbaiki setelah deploy versi upstream terbaru dan menonaktifkan precompile untuk CSS (diserve secara real-time). Karena ada isu dengan asset precompile.
