### ISSUE TITLE
Authorize giosakti in Github auth

### ISSUE THREAD

**Issue by sidiqpermana** [deeptechid/forem#7]
Hola Maintainer

Ini reproduce nya pas connect akun github ke web diskusi.tech

<img width="729" alt="Screen Shot 2020-09-29 at 13 38 41" src="https://user-images.githubusercontent.com/4090245/94522230-831d1c00-0259-11eb-8734-b91ce3abf5be.png">

**Comment by giosakti** [comment]
thanks for catching this, we have transferred ownership of this application to `deeptechid` organization
