### ISSUE TITLE
Button Continue TnC unable to click

### ISSUE THREAD

**Issue by sidiqpermana** [deeptechid/forem#8]
Reproduce after connecting to github then the Button Continue as shown below isn't able to click, seems like still disable.

Thanks
<img width="776" alt="Screen Shot 2020-09-29 at 13 46 48" src="https://user-images.githubusercontent.com/4090245/94522779-60d7ce00-025a-11eb-9b6d-98731240b66b.png">

**Comment by giosakti** [comment]
Can you check this mas, for now have to follow the workaround
https://github.com/deeptechid/forem/issues/6

**Comment by giosakti** [comment]
closing this in favor of #6 (duplicate)
